### ISSUE TITLE
大神，请问要怎么让列宽根据表格文字自动调整? 文字要怎么设置居中?

### ISSUE THREAD

**Issue by NekoOkawari** [wangerzi/layui-excel#10]

**Comment by wangerzi** [comment]
列宽根据文本调整，还没有这个功能，需要以数据长度做估算，取每一列最大的数据长度。文字居中可以看一下 [样式设置专区](https://github.com/wangerzi/layui-excel#%E6%A0%B7%E5%BC%8F%E8%AE%BE%E7%BD%AE%E4%B8%93%E5%8C%BA)
