### ISSUE TITLE
使用回调方式导出时，表头设置问题

### ISSUE THREAD

**Issue by EzraZhao** [wangerzi/layui-excel#13]
使用回调方式导出，若function返回值非value，会把表头覆盖掉。

**Comment by wangerzi** [comment]
回调梳理是全单元格的，在处理过程中表头和纯数据一视同仁，所以如下两种解决方法
1. 针对表头数据做下特殊处理直接返回 value
2. 回调的filter函数只针对纯数据，表头按顺序 unshift 进入导出数组
