### ISSUE TITLE
导出操作报错

### ISSUE THREAD

**Issue by Gota-Peng** [wangerzi/layui-excel#20]
您好，我用IE11访问 http://excel.wj2015.com/  点击导出操作报错：SCRIPT5007: 无法获取未定义或 null 引用的属性“apply”。位置是excel.js的14行，用chrome就能正常导出。请问这是怎么回事呢？

**Comment by wangerzi** [comment]
应该是上午群里问的问题吧，v1.6.6 已经解决了。
