### ISSUE TITLE
导出数据列顺序不正确

### ISSUE THREAD

**Issue by onlypeng** [wangerzi/layui-excel#23]
导出数据时如果数据字典key为数值格式时 例如：“12” 数值列会提前 导致列顺序错误 同时也无法通过filterExportData函数排序

**Comment by wangerzi** [comment]
什么环境下呢，如果所有的 key 都是字符串的话，不会有这种问题的，比如 v[“12”] 而不是 v[12]

**Comment by wangerzi** [comment]
ISSUE 有需要再开启吧，这个问题的处理方案已经记录在常见问题中了

![image](https://user-images.githubusercontent.com/22190579/126417524-e2cf4c5f-a4a0-4312-a093-ecc8e18164b2.png)
