### ISSUE TITLE
导入excel时，和layui的upload模块，结合使用应该怎么做呢？尝试了好多方法都没有成功

### ISSUE THREAD

**Issue by lixiaolong41** [wangerzi/layui-excel#24]
根据示例中直接采用input是可以正常导入解析的，但是和upload模块结合使用：
var uploadInst = upload.render({
                auto: false
                , elem: '#import-excel' //绑定元素
                , exts: 'xlsx|xls'
                , choose: function (obj) {
                    obj.preview(function (index, file) {
                        try {
                            excel.importExcel(file, {}, function (data) {
                                console.log(data[0]);
                                data = excel.filterImportData(data, {
                                    'id': 'A'
                                    , 'username': 'B'
                                    , 'experience': 'C'
                                    , 'sex': 'D'
                                    , 'score': 'E'
                                    , 'city': 'F'
                                    , 'classify': 'G'
                                    , 'wealth': 'H'
                                    , 'sign': 'I'
                                });
                                console.log(data);
                            });
                        } catch (e) {
                            layer.alert(e.message);
                        }
                    });
                }
            });
这样就无法正常解析了，且没有报错

**Comment by wangerzi** [comment]
demo 里边有写 upload模块集成的，http://excel.wj2015.com/，至于这里的代码是否存在绑定元素有误等情况就需要结合具体场景而定了。

**Comment by wangerzi** [comment]
没有情况更新就关闭 issue 了。
