### ISSUE TITLE
导出Excel时数值0的单元格输出为空

### ISSUE THREAD

**Issue by tanzx** [wangerzi/layui-excel#3]
导出Excel时数值0的单元格输出为空。原因：xlsx.js中write_ws_xml_cell函数，在cell.v等于0时，返回空字符串。

**Comment by wangerzi** [comment]
v1.5已解决

**Comment by wangerzi** [comment]
不过解决的时候没看到你的issue，，是通过兼容显示为字符串 '0' 加靠右显示实现的，感谢反馈，我找空调一下XLSX.JS的write_ws_xml_cell~
