### ISSUE TITLE
您好，问下，上传一个xlsx里面含有单元格合并，部分字体有颜色/行有高度，通过程序解析后导出没有高度，没有颜色...

### ISSUE THREAD

**Issue by zhuibo66** [wangerzi/layui-excel#32]
我上传的文件：
![image](https://user-images.githubusercontent.com/69130137/131807396-000ef6cf-b703-4178-9f73-4987702ce231.png)

我的代码，直接在官网测试（[http://excel.wj2015.com/](http://excel.wj2015.com/)）：

![image](https://user-images.githubusercontent.com/69130137/131963062-252ff122-661d-4224-b2c7-193079ea072e.png)

想问下，是不是原生的SheetJs在读取xls的时候，本身就没有自带style的数据，导致转换的时候就失败了（换句话说，是不是魔改的还是不彻底，还是需要支持正版？哈哈）

[测试的文件.xlsx](https://github.com/wangerzi/layui-excel/files/7103865/1.xlsx)

**Comment by wangerzi** [comment]
群内讨论过，我就关 issue 了，魔改的法子确实不彻底，有点陈旧了。
