### ISSUE TITLE
setExportCellStyle单元格函数设置样式问题

### ISSUE THREAD

**Issue by skyloong** [wangerzi/layui-excel#9]
setExportCellStyle函数源码有问题
`
var maxCol = data.length -1;
var maxRow = fieldKeys.length - 1 ;
`
这个反过来了吧，应该是这样才对吧
`
var maxCol = fieldKeys.length - 1;
var maxRow = data.length -1;
`

**Comment by wangerzi** [comment]
感谢反馈，刚刚已经修复！
